site_name: Causal Discovery by Cadimulc
#site_url: https://example.com/

nav:
  - Introduction: docs/index.md
  - Quick Tutorials: docs/quick_tutorials.md
  - Data Generation: docs/generation.md
  - Hybrid Causal Algorithms: docs/hybrid_algorithms.md
  - Causal Graph Evaluation: docs/evaluation.md

theme:
  icon:
    logo: material/home
  name: "material"
  features:
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)" # 根据系统的颜色模式自动切换
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: light mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: dark mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          path: [cadimulc]
          options:
            show_source: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
